### ISSUE TITLE
Upgrade v4.2.0-2 to new alpine base image version 3.14.3-1

### ISSUE THREAD

**Issue by Hertucktor** [cloudogu/redmine#90]
The newest alpine base image fixes the ML-Parser Expat (https://github.com/advisories/GHSA-h83g-c7g2-6r9h) security issue

**Comment by CloudFlo2312** [comment]
New version is released: [v4.2.0-3](https://github.com/cloudogu/redmine/releases/tag/v4.2.0-3)

This branch is NOT merged into the develop branch, as the corresponding fix has already been made there.
